"""Update LLMConfig schema

Revision ID: 29b9324931ef
Revises: fb56884cd5a0
Create Date: 2025-12-24 16:30:09.155687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b9324931ef'
down_revision = 'fb56884cd5a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analytics_days', 'project_id',
               existing_type=sa.UUID(),
               comment='Project ID for project-scoped analytics',
               existing_nullable=True)
    op.alter_column('api_keys', 'project_id',
               existing_type=sa.UUID(),
               comment='Project ID for project-scoped API keys',
               existing_nullable=True)
    op.alter_column('chat_messages', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_chat_messages_project_id'), 'chat_messages', ['project_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'projects', ['project_id'], ['id'])
    op.alter_column('crawl_sources', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_crawl_sources_project_id'), 'crawl_sources', ['project_id'], unique=False)
    op.create_foreign_key(None, 'crawl_sources', 'projects', ['project_id'], ['id'])
    op.add_column('llm_configs', sa.Column('chat_model', sa.String(length=100), nullable=True))
    op.add_column('llm_configs', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('llm_configs', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.drop_column('llm_configs', 'model_name')
    op.alter_column('query_logs', 'project_id',
               existing_type=sa.UUID(),
               comment='Project ID for project-scoped queries',
               existing_nullable=True)
    op.drop_column('settings', 'theme_preset')
    op.alter_column('uploaded_documents', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_uploaded_documents_project_id'), 'uploaded_documents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'uploaded_documents', 'projects', ['project_id'], ['id'])
    op.alter_column('webhooks', 'secret',
               existing_type=sa.VARCHAR(length=255),
               comment='Signing secret for webhook payloads',
               existing_comment='Signing secret for payload verification',
               existing_nullable=False)
    op.drop_column('webhooks', 'last_triggered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('webhooks', 'secret',
               existing_type=sa.VARCHAR(length=255),
               comment='Signing secret for payload verification',
               existing_comment='Signing secret for webhook payloads',
               existing_nullable=False)
    op.drop_constraint(None, 'uploaded_documents', type_='foreignkey')
    op.drop_index(op.f('ix_uploaded_documents_project_id'), table_name='uploaded_documents')
    op.alter_column('uploaded_documents', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('settings', sa.Column('theme_preset', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Theme preset: blue, orange, gray, red'))
    op.alter_column('query_logs', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project ID for project-scoped queries',
               existing_nullable=True)
    op.add_column('llm_configs', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('llm_configs', 'api_key')
    op.drop_column('llm_configs', 'embedding_model')
    op.drop_column('llm_configs', 'chat_model')
    op.drop_constraint(None, 'crawl_sources', type_='foreignkey')
    op.drop_index(op.f('ix_crawl_sources_project_id'), table_name='crawl_sources')
    op.alter_column('crawl_sources', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_project_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('api_keys', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project ID for project-scoped API keys',
               existing_nullable=True)
    op.alter_column('analytics_days', 'project_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Project ID for project-scoped analytics',
               existing_nullable=True)
    # ### end Alembic commands ###
