"""add_user_sessions_table

Revision ID: 3e953203324d
Revises: ea78dfd717fd
Create Date: 2026-01-15 11:19:47.633518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e953203324d'
down_revision = 'ea78dfd717fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatars_id'), table_name='avatars')
    op.drop_index(op.f('ix_avatars_is_active'), table_name='avatars')
    op.drop_index(op.f('ix_avatars_is_default'), table_name='avatars')
    op.drop_index(op.f('ix_avatars_name'), table_name='avatars')
    op.drop_table('avatars')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('avatars',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment="Avatar identifier (e.g., 'avatar-1', 'avatar-2')"),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Display name for the avatar'),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='URL to the avatar image (relative path or full URL)'),
    sa.Column('image_data', sa.TEXT(), autoincrement=False, nullable=True, comment='Base64 encoded image data (alternative to image_url)'),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether this is a default avatar'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether this avatar is available'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='Sort order for display'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('avatars_pkey'))
    )
    op.create_index(op.f('ix_avatars_name'), 'avatars', ['name'], unique=True)
    op.create_index(op.f('ix_avatars_is_default'), 'avatars', ['is_default'], unique=False)
    op.create_index(op.f('ix_avatars_is_active'), 'avatars', ['is_active'], unique=False)
    op.create_index(op.f('ix_avatars_id'), 'avatars', ['id'], unique=False)
    # ### end Alembic commands ###
