"""make_chat_model_nullable

Revision ID: 3eb16079f68f
Revises: p1q2r3s4t5u6
Create Date: 2026-06-08 12:30:37.101334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb16079f68f'
down_revision = 'p1q2r3s4t5u6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatbot_settings', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Chat model name')
    op.alter_column('llm_configs', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_configs', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('chatbot_settings', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Chat model name')
    # ### end Alembic commands ###
