"""Add sources column to chat_messages

Revision ID: 6e4a9c94102a
Revises: add_user_id_user_scoping
Create Date: 2025-12-18 16:12:10.942325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4a9c94102a'
down_revision = 'add_user_id_user_scoping'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sources', sa.JSON(), nullable=True, comment='TopK sources/results for search queries'))
    op.drop_index(op.f('ix_chat_messages_feedback_created'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_tag'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_tag_created'), table_name='chat_messages')
    op.drop_column('chat_messages', 'tag')
    op.alter_column('query_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='User ID (nullable for API-key or anonymous queries)',
               existing_nullable=True)
    op.drop_index(op.f('ix_query_logs_module'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_module_timestamp'), table_name='query_logs')
    op.drop_column('query_logs', 'module')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Module name: overview, crawl, documents, rag_tuning, analytics, feedback, integrations'))
    op.create_index(op.f('ix_query_logs_module_timestamp'), 'query_logs', ['module', 'timestamp'], unique=False)
    op.create_index(op.f('ix_query_logs_module'), 'query_logs', ['module'], unique=False)
    op.alter_column('query_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User ID (nullable for API-key or anonymous queries)',
               existing_nullable=True)
    op.add_column('chat_messages', sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Feedback tag: helpful, outdated, accurate, complete, etc.'))
    op.create_index(op.f('ix_chat_messages_tag_created'), 'chat_messages', ['tag', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_tag'), 'chat_messages', ['tag'], unique=False)
    op.create_index(op.f('ix_chat_messages_feedback_created'), 'chat_messages', ['feedback', 'created_at'], unique=False)
    op.drop_column('chat_messages', 'sources')
    # ### end Alembic commands ###
