"""Add user profile fields

Revision ID: 85653b6200ca
Revises: 778d9ced9f4d
Create Date: 2026-01-06 20:27:44.239357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85653b6200ca'
down_revision = '778d9ced9f4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_crawl_urls_error_type'), table_name='failed_crawl_urls')
    op.drop_index(op.f('ix_failed_crawl_urls_failed_at'), table_name='failed_crawl_urls')
    op.drop_index(op.f('ix_failed_crawl_urls_id'), table_name='failed_crawl_urls')
    op.drop_index(op.f('ix_failed_crawl_urls_job_id'), table_name='failed_crawl_urls')
    op.drop_index(op.f('ix_failed_crawl_urls_source_id'), table_name='failed_crawl_urls')
    op.drop_index(op.f('ix_failed_crawl_urls_url'), table_name='failed_crawl_urls')
    op.drop_table('failed_crawl_urls')
    op.alter_column('chatbot_settings', 'project_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Project ID for project-scoped chatbot settings')
    op.alter_column('chatbot_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether chatbot/chat is enabled',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbot_settings', 'widget_avatar',
               existing_type=sa.TEXT(),
               comment='Widget avatar identifier or URL (can be base64 data URL)',
               existing_comment='Widget avatar identifier or URL',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'model_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='LLM provider (openai, mistral, gemini, ollama)',
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('chatbot_settings', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Chat model name',
               existing_server_default=sa.text("'gpt-4'::character varying"))
    op.alter_column('chatbot_settings', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               comment='API key for the LLM provider',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Embedding model name',
               existing_server_default=sa.text("'text-embedding-3-small'::character varying"))
    op.alter_column('chatbot_settings', 'chat_temperature',
               existing_type=sa.VARCHAR(length=10),
               comment='Temperature for chat (0.0-2.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_top_p',
               existing_type=sa.VARCHAR(length=10),
               comment='Top P for chat (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_best_of',
               existing_type=sa.INTEGER(),
               comment='Best Of for chat (positive integer)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_frequency_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment='Frequency penalty for chat (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_presence_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment='Presence penalty for chat (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_top_k',
               existing_type=sa.INTEGER(),
               comment='Number of documents to retrieve for chat',
               existing_nullable=True,
               existing_server_default=sa.text('8'))
    op.alter_column('chatbot_settings', 'chat_similarity_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Minimum similarity score for document inclusion in chat (0.0-1.0)',
               existing_nullable=True,
               existing_server_default=sa.text("'0.7'::double precision"))
    op.alter_column('chatbot_settings', 'chat_max_tokens',
               existing_type=sa.INTEGER(),
               comment='Maximum tokens for chat responses (0-1000, 0=unlimited)',
               existing_nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('chatbot_settings', 'chat_use_reranker',
               existing_type=sa.BOOLEAN(),
               comment='Use reranker to improve result relevance in chat',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_chatbot_settings_project_id'), 'chatbot_settings', ['project_id'], unique=False)
    op.create_index(op.f('ix_chatbot_settings_user_id'), 'chatbot_settings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chatbot_settings', 'projects', ['project_id'], ['id'])
    op.alter_column('crawl_sources', 'trained_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when crawled data was successfully trained/embedded',
               existing_nullable=True)
    op.alter_column('llm_configs', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('llm_configs', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('search_settings', 'model_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='LLM provider (openai, mistral, gemini, ollama)',
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('search_settings', 'search_model',
               existing_type=sa.VARCHAR(length=100),
               comment='Search model name',
               existing_nullable=True)
    op.alter_column('search_settings', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               comment='API key for the LLM provider',
               existing_nullable=True)
    op.alter_column('search_settings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Embedding model name',
               existing_server_default=sa.text("'text-embedding-3-small'::character varying"))
    op.alter_column('search_settings', 'search_temperature',
               existing_type=sa.VARCHAR(length=10),
               comment='Temperature for search (0.0-2.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_top_p',
               existing_type=sa.VARCHAR(length=10),
               comment='Top P for search (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_best_of',
               existing_type=sa.INTEGER(),
               comment='Best Of for search (positive integer)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_frequency_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment='Frequency penalty for search (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_presence_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment='Presence penalty for search (-2.0 to 2.0)',
               existing_nullable=True)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'location')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'department')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'full_name')
    op.alter_column('search_settings', 'search_presence_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Presence penalty for search (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_frequency_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Frequency penalty for search (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_best_of',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Best Of for search (positive integer)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_top_p',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Top P for search (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_temperature',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Temperature for search (0.0-2.0)',
               existing_nullable=True)
    op.alter_column('search_settings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='Embedding model name',
               existing_server_default=sa.text("'text-embedding-3-small'::character varying"))
    op.alter_column('search_settings', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='API key for the LLM provider',
               existing_nullable=True)
    op.alter_column('search_settings', 'search_model',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Search model name',
               existing_nullable=True)
    op.alter_column('search_settings', 'model_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='LLM provider (openai, mistral, gemini, ollama)',
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('llm_configs', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('llm_configs', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('crawl_sources', 'trained_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when crawled data was successfully trained/embedded',
               existing_nullable=True)
    op.drop_constraint(None, 'chatbot_settings', type_='foreignkey')
    op.drop_index(op.f('ix_chatbot_settings_user_id'), table_name='chatbot_settings')
    op.drop_index(op.f('ix_chatbot_settings_project_id'), table_name='chatbot_settings')
    op.alter_column('chatbot_settings', 'chat_use_reranker',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Use reranker to improve result relevance in chat',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('chatbot_settings', 'chat_max_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum tokens for chat responses (0-1000, 0=unlimited)',
               existing_nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('chatbot_settings', 'chat_similarity_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Minimum similarity score for document inclusion in chat (0.0-1.0)',
               existing_nullable=True,
               existing_server_default=sa.text("'0.7'::double precision"))
    op.alter_column('chatbot_settings', 'chat_top_k',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of documents to retrieve for chat',
               existing_nullable=True,
               existing_server_default=sa.text('8'))
    op.alter_column('chatbot_settings', 'chat_presence_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Presence penalty for chat (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_frequency_penalty',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Frequency penalty for chat (-2.0 to 2.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_best_of',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Best Of for chat (positive integer)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_top_p',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Top P for chat (0.0-1.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_temperature',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Temperature for chat (0.0-2.0)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='Embedding model name',
               existing_server_default=sa.text("'text-embedding-3-small'::character varying"))
    op.alter_column('chatbot_settings', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='API key for the LLM provider',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='Chat model name',
               existing_server_default=sa.text("'gpt-4'::character varying"))
    op.alter_column('chatbot_settings', 'model_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='LLM provider (openai, mistral, gemini, ollama)',
               existing_server_default=sa.text("'openai'::character varying"))
    op.alter_column('chatbot_settings', 'widget_avatar',
               existing_type=sa.TEXT(),
               comment='Widget avatar identifier or URL',
               existing_comment='Widget avatar identifier or URL (can be base64 data URL)',
               existing_nullable=True)
    op.alter_column('chatbot_settings', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether chatbot/chat is enabled',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbot_settings', 'project_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='Project ID for project-scoped chatbot settings')
    op.create_table('failed_crawl_urls',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False, comment='Crawl source ID'),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True, comment='Crawl job ID'),
    sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False, comment='Failed URL'),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Type of error: HTTP_404, HTTP_500, CONNECTION_ERROR, TIMEOUT, etc.'),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True, comment='HTTP status code if applicable'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed error message'),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of retry attempts made'),
    sa.Column('failed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when the URL failed'),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], name=op.f('fk_failed_crawl_urls_job_id')),
    sa.ForeignKeyConstraint(['source_id'], ['crawl_sources.id'], name=op.f('fk_failed_crawl_urls_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('failed_crawl_urls_pkey')),
    comment='Track URLs that failed to crawl (404s, connection errors, etc.)'
    )
    op.create_index(op.f('ix_failed_crawl_urls_url'), 'failed_crawl_urls', ['url'], unique=False)
    op.create_index(op.f('ix_failed_crawl_urls_source_id'), 'failed_crawl_urls', ['source_id'], unique=False)
    op.create_index(op.f('ix_failed_crawl_urls_job_id'), 'failed_crawl_urls', ['job_id'], unique=False)
    op.create_index(op.f('ix_failed_crawl_urls_id'), 'failed_crawl_urls', ['id'], unique=False)
    op.create_index(op.f('ix_failed_crawl_urls_failed_at'), 'failed_crawl_urls', ['failed_at'], unique=False)
    op.create_index(op.f('ix_failed_crawl_urls_error_type'), 'failed_crawl_urls', ['error_type'], unique=False)
    # ### end Alembic commands ###
