"""Initial migration

Revision ID: eea47e3ef963
Revises: 
Create Date: 2025-09-30 16:41:03.985910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eea47e3ef963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_pages_id'), 'crawl_pages', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_job_id'), 'crawl_pages', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_url'), 'crawl_pages', ['url'], unique=False)
    op.create_table('crawl_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_targets_id'), 'crawl_targets', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_targets_name'), 'crawl_targets', ['name'], unique=False)
    op.create_index(op.f('ix_crawl_targets_url'), 'crawl_targets', ['url'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('idx_content_hash'), table_name='crawled_content', if_exists=True)
    op.drop_index(op.f('idx_crawled_at'), table_name='crawled_content', if_exists=True)
    op.drop_index(op.f('idx_job_id'), table_name='crawled_content', if_exists=True)
    op.drop_index(op.f('idx_url'), table_name='crawled_content', if_exists=True)
    op.drop_table('crawled_content', if_exists=True)
    op.drop_index(op.f('ix_crawl_results_id'), table_name='crawl_results', if_exists=True)
    op.drop_index(op.f('ix_crawl_results_url'), table_name='crawl_results', if_exists=True)
    op.drop_index(op.f('ix_crawl_results_website_config_id'), table_name='crawl_results', if_exists=True)
    op.drop_table('crawl_results', if_exists=True)
    op.drop_index(op.f('ix_website_configs_id'), table_name='website_configs', if_exists=True)
    op.drop_table('website_configs', if_exists=True)
    op.drop_index(op.f('ix_access_permissions_id'), table_name='access_permissions', if_exists=True)
    op.drop_index(op.f('ix_access_permissions_website_config_id'), table_name='access_permissions', if_exists=True)
    op.drop_table('access_permissions', if_exists=True)
    op.add_column('crawl_jobs', sa.Column('target_id', sa.Integer(), nullable=False))
    op.add_column('crawl_jobs', sa.Column('pages_crawled', sa.Integer(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('crawl_jobs', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('crawl_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('crawl_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('crawl_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_crawl_jobs_id'), 'crawl_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_target_id'), 'crawl_jobs', ['target_id'], unique=False)
    op.drop_column('crawl_jobs', 'url')
    op.drop_column('crawl_jobs', 'error')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('crawl_jobs', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_crawl_jobs_target_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_id'), table_name='crawl_jobs')
    op.alter_column('crawl_jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('crawl_jobs', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('crawl_jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('crawl_jobs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('crawl_jobs', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('crawl_jobs', 'error_message')
    op.drop_column('crawl_jobs', 'pages_crawled')
    op.drop_column('crawl_jobs', 'target_id')
    op.create_table('access_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('website_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permission_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['website_config_id'], ['website_configs.id'], name=op.f('access_permissions_website_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('access_permissions_pkey'))
    )
    op.create_index(op.f('ix_access_permissions_website_config_id'), 'access_permissions', ['website_config_id'], unique=False)
    op.create_index(op.f('ix_access_permissions_id'), 'access_permissions', ['id'], unique=False)
    op.create_table('website_configs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('website_configs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('max_depth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crawl_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('respect_robots_txt', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sitemap_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ignore_file_extensions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exclusion_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('legal_crawl_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('login_credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allowlist_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('denylist_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('access_tokens', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='website_configs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_website_configs_id'), 'website_configs', ['id'], unique=False)
    op.create_table('crawl_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('website_config_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('internal_links_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('external_links_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crawl_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['website_config_id'], ['website_configs.id'], name=op.f('crawl_results_website_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crawl_results_pkey'))
    )
    op.create_index(op.f('ix_crawl_results_website_config_id'), 'crawl_results', ['website_config_id'], unique=False)
    op.create_index(op.f('ix_crawl_results_url'), 'crawl_results', ['url'], unique=False)
    op.create_index(op.f('ix_crawl_results_id'), 'crawl_results', ['id'], unique=False)
    op.create_table('crawled_content',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crawled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], name=op.f('crawled_content_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crawled_content_pkey'))
    )
    op.create_index(op.f('idx_url'), 'crawled_content', ['url'], unique=False)
    op.create_index(op.f('idx_job_id'), 'crawled_content', ['job_id'], unique=False)
    op.create_index(op.f('idx_crawled_at'), 'crawled_content', ['crawled_at'], unique=False)
    op.create_index(op.f('idx_content_hash'), 'crawled_content', ['content_hash'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_crawl_targets_url'), table_name='crawl_targets')
    op.drop_index(op.f('ix_crawl_targets_name'), table_name='crawl_targets')
    op.drop_index(op.f('ix_crawl_targets_id'), table_name='crawl_targets')
    op.drop_table('crawl_targets')
    op.drop_index(op.f('ix_crawl_pages_url'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_job_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    # ### end Alembic commands ###
