import { useMemo } from 'react';

import { useTranslation } from '@/i18n';

const TIMEZONE_KEYS = [
  { value: 'America/Los_Angeles', key: 'profile.timezones.pacific' },
  { value: 'America/Denver', key: 'profile.timezones.mountain' },
  { value: 'America/Chicago', key: 'profile.timezones.central' },
  { value: 'America/New_York', key: 'profile.timezones.eastern' },
  { value: 'Europe/London', key: 'profile.timezones.gmt' },
  { value: 'Europe/Berlin', key: 'profile.timezones.cet' },
] as const;

const DEPARTMENT_KEYS = {
  Engineering: 'profile.departments.engineering',
  Product: 'profile.departments.product',
  Design: 'profile.departments.design',
  Marketing: 'profile.departments.marketing',
  Sales: 'profile.departments.sales',
  Operations: 'profile.departments.operations',
} as const;

export function useProfileCopy() {
  const { t } = useTranslation();

  return useMemo(
    () => ({
      title: t('profile.title'),
      subtitle: t('profile.subtitle'),
      save: t('profile.actions.save'),
      saving: t('profile.actions.saving'),
      tabs: { general: t('profile.tabs.general'), security: t('profile.tabs.security') },
      sections: {
        personal: {
          title: t('profile.sections.personal.title'),
          description: t('profile.sections.personal.description'),
        },
        contact: {
          title: t('profile.sections.contact.title'),
          description: t('profile.sections.contact.description'),
        },
        password: {
          title: t('profile.sections.security.password.title'),
          description: t('profile.sections.security.password.description'),
        },
        security: {
          title: t('profile.sections.security.options.title'),
          description: t('profile.sections.security.options.description'),
        },
      },
      fields: {
        username: t('profile.fields.username'),
        email: t('profile.fields.email'),
        emailLocked: t('profile.fields.emailLocked'),
        jobTitle: t('profile.fields.jobTitle'),
        jobTitlePlaceholder: t('profile.fields.jobTitlePlaceholder'),
        department: t('profile.fields.department'),
        departmentPlaceholder: t('profile.fields.departmentPlaceholder'),
        phone: t('profile.fields.phone'),
        phonePlaceholder: t('profile.fields.phonePlaceholder'),
        location: t('profile.fields.location'),
        timezone: t('profile.fields.timezone'),
        timezonePlaceholder: t('profile.fields.timezonePlaceholder'),
        bio: t('profile.fields.bio'),
        bioPlaceholder: t('profile.fields.bioPlaceholder'),
        currentPassword: t('profile.fields.currentPassword'),
        currentPasswordPlaceholder: t('profile.fields.currentPasswordPlaceholder'),
        newPassword: t('profile.fields.newPassword'),
        newPasswordPlaceholder: t('profile.fields.newPasswordPlaceholder'),
        confirmPassword: t('profile.fields.confirmPassword'),
        confirmPasswordPlaceholder: t('profile.fields.confirmPasswordPlaceholder'),
        updatePassword: t('profile.actions.updatePassword'),
        updatingPassword: t('profile.actions.updatingPassword'),
      },
      departments: Object.fromEntries(
        Object.entries(DEPARTMENT_KEYS).map(([key, labelKey]) => [key, t(labelKey)]),
      ) as Record<keyof typeof DEPARTMENT_KEYS, string>,
      timezones: TIMEZONE_KEYS.map((option) => ({
        value: option.value,
        label: t(option.key),
      })),
      security: {
        totpTitle: t('profile.security.totp.title'),
        totpEnabled: t('profile.security.totp.enabled'),
        totpDisabled: t('profile.security.totp.disabled'),
        email2faTitle: t('profile.security.email2fa.title'),
        email2faEnabled: t('profile.security.email2fa.enabled'),
        email2faDisabled: t('profile.security.email2fa.disabled'),
        loginNotificationsTitle: t('profile.security.loginNotifications.title'),
        loginNotificationsDescription: t('profile.security.loginNotifications.description'),
        sessionsTitle: t('profile.security.sessions.title'),
        sessionsDescription: t('profile.security.sessions.description'),
        sessionsView: t('profile.security.sessions.view'),
        enable: t('profile.security.totp.enable'),
        disable: t('profile.security.totp.disable'),
        settingUp: t('profile.security.totp.settingUp'),
        generating: t('profile.security.totp.generating'),
        backupCodes: t('profile.security.totp.backupCodes'),
        processing: t('profile.security.email2fa.processing'),
      },
      sessions: {
        title: t('profile.sessions.title'),
        description: t('profile.sessions.description'),
        loading: t('profile.sessions.loading'),
        loadFailed: t('profile.sessions.loadFailed'),
        loadFailedHint: t('profile.sessions.loadFailedHint'),
        currentTitle: t('profile.sessions.currentTitle'),
        currentBadge: t('profile.sessions.currentBadge'),
        currentDescription: t('profile.sessions.currentDescription'),
        otherTitle: t('profile.sessions.otherTitle'),
        otherDescription: (count: number) => t('profile.sessions.otherDescription', { count }),
        revokeAll: t('profile.sessions.revokeAll'),
        revoking: t('profile.sessions.revoking'),
        revoke: t('profile.sessions.revoke'),
        lastActive: t('profile.sessions.lastActive'),
        loggedIn: t('profile.sessions.loggedIn'),
        noOtherSessions: t('profile.sessions.noOtherSessions'),
        onlyThisDevice: t('profile.sessions.onlyThisDevice'),
        noneFound: t('profile.sessions.noneFound'),
        confirmRevokeTitle: t('profile.sessions.confirmRevokeTitle'),
        confirmRevokeDescription: t('profile.sessions.confirmRevokeDescription'),
        confirmRevokeAction: t('profile.sessions.confirmRevokeAction'),
        confirmRevokeAllTitle: t('profile.sessions.confirmRevokeAllTitle'),
        confirmRevokeAllDescription: t('profile.sessions.confirmRevokeAllDescription'),
        confirmRevokeAllCount: (count: number) => t('profile.sessions.confirmRevokeAllCount', { count }),
        confirmRevokeAllAction: t('profile.sessions.confirmRevokeAllAction'),
        cancel: t('common.cancel'),
        close: t('profile.sessions.close'),
      },
      joined: (date: string) => t('profile.summary.joined', { date }),
      badge: { admin: t('profile.badge.admin'), user: t('profile.badge.user') },
      toast: {
        fileTooLarge: t('profile.toast.fileTooLarge.description'),
        invalidFileType: t('profile.toast.invalidFileType.description'),
        avatarUpdated: t('profile.toast.avatarUpdated'),
        setup2faStarted: {
          title: t('profile.toast.2fa.setupStarted.title'),
          description: t('profile.toast.2fa.setupStarted.description'),
        },
        twoFactorEnabled: {
          title: t('profile.toast.2fa.enabled.title'),
          description: t('profile.toast.2fa.enabled.description'),
        },
        backupCodesGenerated: {
          title: t('profile.toast.backupCodes.title'),
          description: t('profile.toast.backupCodes.description'),
        },
      },
      dialogs: {
        setup2fa: {
          title: t('profile.dialogs.setup2fa.title'),
          description: t('profile.dialogs.setup2fa.description'),
          verify: t('profile.dialogs.setup2fa.verify'),
        },
        verify2fa: {
          title: t('profile.dialogs.verify2fa.title'),
          description: t('profile.dialogs.verify2fa.description'),
          codeLabel: t('profile.dialogs.verify2fa.codeLabel'),
          codePlaceholder: t('profile.dialogs.verify2fa.codePlaceholder'),
          verifying: t('profile.dialogs.verify2fa.verifying'),
          verifyAndEnable: t('profile.dialogs.verify2fa.verifyAndEnable'),
        },
        disable2fa: {
          title: t('profile.dialogs.disable2fa.title'),
          description: t('profile.dialogs.disable2fa.description'),
          passwordLabel: t('profile.dialogs.disable2fa.passwordLabel'),
          passwordPlaceholder: t('profile.dialogs.disable2fa.passwordPlaceholder'),
          codeLabel: t('profile.dialogs.disable2fa.codeLabel'),
          codePlaceholder: t('profile.dialogs.disable2fa.codePlaceholder'),
          codeHelper: t('profile.dialogs.disable2fa.codeHelper'),
          disabling: t('profile.dialogs.disable2fa.disabling'),
          disable: t('profile.dialogs.disable2fa.disable'),
        },
        backupCodes: {
          title: t('profile.dialogs.backupCodes.title'),
          description: t('profile.dialogs.backupCodes.description'),
          notice: t('profile.dialogs.backupCodes.notice'),
          saved: t('profile.dialogs.backupCodes.saved'),
          copy: t('profile.dialogs.backupCodes.copy'),
          copied: t('profile.dialogs.backupCodes.copied'),
        },
        email2fa: {
          enableTitle: t('profile.dialogs.email2fa.enableTitle'),
          disableTitle: t('profile.dialogs.email2fa.disableTitle'),
          enableDescription: t('profile.dialogs.email2fa.enableDescription'),
          disableDescription: t('profile.dialogs.email2fa.disableDescription'),
          passwordLabel: t('profile.dialogs.email2fa.passwordLabel'),
          passwordPlaceholder: t('profile.dialogs.email2fa.passwordPlaceholder'),
        },
        cancel: t('common.cancel'),
      },
    }),
    [t],
  );
}
