import { brandTokens } from '@/theme/brand-tokens';

const { color, dark } = brandTokens;

/** Palette aligned with RAGSuite brand tokens (`tokens/design-tokens.json`). */
export const colors = {
  light: {
    background: color.paper,
    surface: color.paperRaised,
    surfaceMuted: color.paperSunken,
    border: color.hairline,
    borderStrong: color.hairlineStrong,
    text: color.ink,
    textSoft: color.inkSoft,
    textMuted: color.inkFaint,
    textOnPrimary: color.paperRaised,
    primary: color.pineBright,
    primaryPressed: color.pine,
    primaryTint: color.pineTint,
    /** Foreground on primaryTint soft surfaces (nav active, success pills). */
    onPrimaryTint: color.pineBright,
    sidebar: color.paperSunken,
    sidebarAccent: color.pineTint,
    sidebarForeground: color.inkSoft,
    success: color.success,
    warning: color.warning,
    danger: color.error,
    dangerBackground: color.ochreTint,
    ochre: color.ochre,
    ochreTint: color.ochreTint,
    pineDeep: color.pineDeep,
    iconMuted: color.inkFaint,
  },
  dark: {
    background: color.pineDeep,
    surface: dark.surfaceRaised,
    surfaceMuted: dark.surfaceSunken,
    border: dark.borderHairline,
    borderStrong: dark.borderStrong,
    text: color.paperRaised,
    textSoft: dark.textSecondary,
    textMuted: dark.textFaint,
    textOnPrimary: color.paperRaised,
    primary: color.pineBright,
    primaryPressed: dark.primaryPressed,
    primaryTint: dark.primaryTintWash,
    onPrimaryTint: dark.primarySoftFg,
    sidebar: color.pineDeep,
    sidebarAccent: dark.surfaceRaised,
    sidebarForeground: dark.textSecondary,
    success: color.success,
    warning: color.warning,
    danger: color.error,
    dangerBackground: dark.dangerSoftBg,
    ochre: color.ochre,
    ochreTint: color.ochreTint,
    pineDeep: color.pineDeep,
    iconMuted: dark.iconMuted,
  },
} as const;
